# Generated by Django 5.0.7 on 2024-07-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_alter_game_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
    ]
