# Generated by Django 5.0.7 on 2024-07-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
